name: "byr-topten"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: generate
        run: ./.github/run.sh
        env:
          BYR_USERNAME: ${{ secrets.BYR_USERNAME }}
          BYR_PASSWORD: ${{ secrets.BYR_PASSWORD }}
      - name: commit
        run: |
          git config --global user.name 'bot'
          git config --global user.email 'bot@github.com'
          git add .
          git commit -am "commit-by-action: $(date)"
          git push
