name: "fetch"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 */6 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: build
        run: ./.github/build.sh

      - name: fetch
        run: /tmp/fetch
        env:
          BYR_USERNAME: ${{ secrets.BYR_USERNAME }}
          BYR_PASSWORD: ${{ secrets.BYR_PASSWORD }}
      - name: fetch-commit
        run: /tmp/commiter -add . -msg "fetch by action"

      - name: render
        run: /tmp/render
      - name: render-commit
        run: /tmp/commiter -add . -msg "render by action" -branch gh-pages -force
