name: "fetch"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: generate
        run: ./.github/fetch.sh
        env:
          BYR_USERNAME: ${{ secrets.BYR_USERNAME }}
          BYR_PASSWORD: ${{ secrets.BYR_PASSWORD }}
      - name: commit
        run: ./.github/commit_fetch.sh
